CREATE ROLE Client NOCREATEDB NOSUPERUSER;
CREATE ROLE Administrator NOSUPERUSER NOCREATEDB;
CREATE ROLE Unauthorized NOSUPERUSER NOCREATEDB;
CREATE ROLE Manager NOSUPERUSER NOCREATEDB;

GRANT ALL PRIVILEGES ON SCHEMA BA TO Unauthorized;
GRANT SELECT ON BA.banks TO Unauthorized;
GRANT SELECT ON BA.products TO Unauthorized;
GRANT INSERT ON BA.users TO Unauthorized;
GRANT INSERT ON BA.clients TO Unauthorized;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA BA TO Unauthorized;

GRANT ALL PRIVILEGES ON SCHEMA BA TO Client;
GRANT SELECT, UPDATE, INSERT ON BA.requests TO Client;
GRANT SELECT ON BA.products TO Client;
GRANT SELECT ON BA.banks TO Client;
GRANT ALL PRIVILEGES ON BA.clients TO Client;
GRANT SELECT, DELETE, UPDATE ON BA.users TO Client;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA BA TO Client;

GRANT ALL PRIVILEGES ON SCHEMA BA TO Manager;
GRANT ALL PRIVILEGES ON BA.clients TO Manager;
GRANT SELECT, UPDATE ON BA.requests TO Manager;
GRANT ALL PRIVILEGES ON BA.products TO Manager;
GRANT ALL PRIVILEGES ON BA.banks TO Manager;
GRANT SELECT, DELETE, UPDATE ON BA.users TO Manager;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA BA TO Manager;

GRANT ALL PRIVILEGES ON SCHEMA BA TO Administrator;
GRANT ALL PRIVILEGES ON BA.clients TO Administrator;
GRANT ALL PRIVILEGES ON BA.users TO Administrator;
GRANT ALL PRIVILEGES ON BA.banks TO Administrator;
GRANT ALL PRIVILEGES ON BA.requests TO Administrator;
GRANT ALL PRIVILEGES ON BA.managers TO Administrator;
GRANT ALL PRIVILEGES ON BA.products TO Administrator;

-- SET ROLE Administrator;
-- SET ROLE Unauthorized;
-- SET ROLE Client;
-- SET ROLE Manager;
-- SET ROLE postgres;

