#!/bin/bash
export PGPASSWORD="admin"
psql -h localhost --port 5435 -U postgres -d postgres < ../../src/data_access/sql_scripts/create.sql
psql -h localhost --port 5435 -U postgres -d postgres < ../../src/data_access/sql_scripts/fill_tables.sql
