name: C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]
jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
      - name: install gtest and gmock
        run: |
          sudo apt install -y libgtest-dev libgmock-dev
          sudo apt-get install cmake
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp lib/*.a /usr/lib
          sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a
          sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
          
      - uses: actions/checkout@v1
      - name: building
        run: |
          cd /home/runner/work/BMSTU_TaDS_LABS_SEM7/BMSTU_TaDS_LABS_SEM7/lab_01/test/unit_tests_BL/
          make testsUserMock.exe
          make testsManager.exe
          make testsClient.exe
          make testsBank.exe
          make testsProduct.exe
          make testsRequest.exe
      - name: testing
        run: /home/runner/work/BMSTU_TaDS_LABS_SEM7/BMSTU_TaDS_LABS_SEM7/lab_01/test/unit_tests_BL/run_tests_bl
        
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"
    - name: se
      run: echo "1" && pwd
